### ISSUE TITLE
Add a login button (not a checkbox)

### ISSUE THREAD

**Issue by Venuchander** [Avdhesh-Varshney/Jarvis#10]
# Remove login Checkbox

Suggestion: It would be nice if we added a Login Button rather than a Checkbox

![Screenshot 2024-06-02 at 22-32-53 Streamlit](https://github.com/Avdhesh-Varshney/Jarvis/assets/106867270/74a22f3f-f5d3-4ad8-8cc9-3d09ec9b3fec)

#SSOC

**Comment by Venuchander** [comment]
Assign me this task.

**Comment by Adii0906** [comment]
but i think the user has the choice whether he wants to signup or login..

**Comment by Avdhesh-Varshney** [comment]
@Venuchander you should first try, report about it on discord server.
Link is present in the main readme file.
