### ISSUE TITLE
🧑‍💻: Add Password Strength Validation (8 Characters, Special Character, and Digit)

### ISSUE THREAD

**Issue by prakrutipathak** [Avdhesh-Varshney/Jarvis#118]
:red_circle: **Add Password Strength Validation (8 Characters, Special Character, and Digit)**: 
:red_circle: **Currently, the project does not have strong password validation. This can lead to security vulnerabilities as users might set weak passwords. I propose adding a feature to validate passwords**: 
:red_circle: **Changes**: I propose adding a feature to validate passwords based on the following criteria:

- Password must be at least 8 characters long.
- Password must contain at least one special character.
- Password must contain at least one digit.

### Screenshots 📷
![Screenshot 2024-10-03 112052](https://github.com/user-attachments/assets/92520c37-61f5-40d6-a2e9-7b14c427f061)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Prakruti Pathak
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Mahesh2k5** [comment]
I wish to contribute to this.
I can add this feature.
can you please assign this to me and gssoc and relevant labels.

**Comment by garvender004** [comment]
hello i would like to contribute .
I am a gssoc contributor.

**Comment by ramu-nukavarapu** [comment]
Password validation is crucial while performing security. I can add the password validation to this.
@prakrutipathak can you assign this issue to me. I'll work on this.

**Comment by jaidh01** [comment]
Hi @Avdhesh-Varshney,
I can solve this issue.
Please assign this to me.

**Comment by jaidh01** [comment]
Hi @Avdhesh-Varshney,
Since you added the High-Priority label to this PR but still it doesn't have any PR linked to it.
So, can you please assign it to me.

**Comment by Mahesh2k5** [comment]
Doesn't this work like first come first serve basis.
