### ISSUE TITLE
📃: Customer Segmentation and Statistical Analysis Enhancements

### ISSUE THREAD

**Issue by sharayuanuse** [Avdhesh-Varshney/Jarvis#126]
:red_circle: **Title**:  Customer Segmentation and Statistical Analysis Enhancements
:red_circle: **Aim**:  To implement customer segmentation and statistical analysis features, including data visualizations and PDF report generation.
:red_circle: **Brief Explanation**:  The Customer Segmentation and Statistical Analysis project focuses on the following key objectives:

- Customer Segmentation:

  - Perform clustering techniques such as KMeans to segment customers based on key features like age, annual income, and spending score.
  - Identify distinct customer groups to enable personalized marketing strategies.
- Statistical Analysis:

  - Generate key statistical metrics such as mean, median, and standard deviation for customer attributes.
  - Perform a detailed analysis of customer demographics and spending patterns.
- Data Visualization:

  - Create visualizations including distribution plots, scatter plots, and correlation heatmaps to present insights.
  - Visualize customer segments in both 2D and 3D spaces for better understanding.
- PDF Report Generation:

  - Generate comprehensive PDF reports including all visualizations and statistical summaries.
  - Provide insights and conclusions based on the data analysis and clustering results.

### Screenshots 📷
![age_distribution](https://github.com/user-attachments/assets/6c6ae374-ada7-4cf9-bc54-52af336002d6)
![age_group_counts](https://github.com/user-attachments/assets/d0037829-1da9-47f0-9104-56d31c0ca467)
![boxplot_spending_score](https://github.com/user-attachments/assets/8510b5ec-9c89-4131-8c28-c846369afd47)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Sharayu Arjun Anuse
- What is your participant role? 
GSSOC, Hacktoberfest
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by garvender004** [comment]
I would like to contribute to this .
Name Garvender
Contributor GSSOC

**Comment by Avdhesh-Varshney** [comment]
This analysis models are not accepted.
