### ISSUE TITLE
🧑‍💻: Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [Avdhesh-Varshney/Jarvis#128]
:red_circle: **Title**: Addition of All Contributors Photos in Readme | Readme Updation
:red_circle: **Enhancement Aim**: We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shariq2003
- What is your participant role? 
GSSOC Ext
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Not required for readme. It is already attached in the application with admin tools.
