### ISSUE TITLE
📃: Text to Image Generator

### ISSUE THREAD

**Issue by jaidh01** [Avdhesh-Varshney/Jarvis#129]
:red_circle: **Title**: Text-to-image generator
:red_circle: **Aim**: To generate an image based on a text.
:red_circle: **Brief Explanation**:  After the completion, in the Image generator section there will be a Image generation bar, which would be able to generate an Image based on the provided text by the user.

* `NOTE`: It does not require any API key.

### Screenshots 📷
It would be able to generate images like this: - 
![generated_image](https://github.com/user-attachments/assets/b2050849-dcdf-4bf3-872d-03b49ea6f53a)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Jai Dhingra
- What is your participant role? GSSOC-extd and Hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by jaidh01** [comment]
Hi @Avdhesh-Varshney, @Sarvesh1523 
I really want to contribute this project please assign it to me.

**Comment by Avdhesh-Varshney** [comment]
@jaidh01 If it is not using API key, it's a GAN-AI Model?

**Comment by jaidh01** [comment]
> @jaidh01 If it is not using API key, it's a GAN-AI Model?

No, it will use a stable diffusion model.
Because of which it uses less memory.

**Comment by jaidh01** [comment]
Hi @Avdhesh-Varshney, @Zedoman,

I hope you're doing well. 
After reviewing the complexity of this task, I believe it would be more appropriate to upgrade the label from `Level 2` to `Level 3`. Could you please consider changing the label accordingly?

Thank you for your time!

**Comment by Avdhesh-Varshney** [comment]
> > @jaidh01 If it is not using API key, it's a GAN-AI Model?
> 
> No, it will use a stable diffusion model. Because of which it uses less memory.

Interesting! Similar to hugging face model.
