### ISSUE TITLE
🐛: Brain Tumor is not working properly

### ISSUE THREAD

**Issue by jaidh01** [Avdhesh-Varshney/Jarvis#130]
:red_circle: **Title**: Brain Tumor is not working properly
:red_circle: **Bug**:  Not working after uploading image
:red_circle: **Changes**:  There is a correction in the code. Where a variable is called without initializing it. So, I just goanna initialize that variable.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/46fb58e4-77e4-4484-b358-9f99882e7bd6)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Jai Dhingra
- What is your participant role?  GSSOC-extd, Hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by aakashmohole** [comment]
can i take this issue
