### ISSUE TITLE
🧑‍💻: Basic Voice Command Features to JARVIS

### ISSUE THREAD

**Issue by pratikwayal01** [Avdhesh-Varshney/Jarvis#144]
---

#### **Description**
Add voice command recognition to JARVIS to support the following features:
1. **Voice Command Recognition**: Listen to user commands.
2. **Application Opening**: Open apps like Calculator, Notepad via voice.
3. **Web Search**: Perform Google searches using voice commands.
4. **Play Music**: Search and play music from YouTube via voice.
5. **Screenshot Capture**: Take screenshots with a voice command, saving them with a custom name.
6. **Greeting**: JARVIS should greet the user upon activation.

#### **Suggested Libraries**
- **SpeechRecognition**: For voice input.
- **os/subprocess**: For opening apps.
- **webbrowser**: For web searches.
- **pytube**: For playing YouTube music.
- **pyautogui**: For capturing screenshots.

---

**Comment by Avdhesh-Varshney** [comment]
This is not a terminal based python program only.
