### ISSUE TITLE
📃: Adding snake game in games section

### ISSUE THREAD

**Issue by Aditijainnn** [Avdhesh-Varshney/Jarvis#145]
:red_circle: **Title**:  Snake game

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role?  gssoc ext and hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhayku2002** [comment]
Abhay
GSSoC'24 Extd
will work on this issue

**Comment by yuvrajj18** [comment]
wanna work on this issue
