### ISSUE TITLE
🧑‍💻: ADD A REMINDER FEATURE 

### ISSUE THREAD

**Issue by harshgupta2125** [Avdhesh-Varshney/Jarvis#149]
:red_circle: **Reminder system **: 
:red_circle: **The user set a task for a particular time and then the jarvis will remind it to do that task.**: 
:red_circle: **Changes**: 

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Harsh Gupta
- What is your participant role? 
Contributor
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by abhayku2002** [comment]
So basically user have to setup the timings and task. And reminder system have remind the task on the particular time.

**Comment by abhayku2002** [comment]
To be Mentioned while taking the issue :

Full name : Abhay Kumar
What is your participant role? gssoc ext

**Comment by harshgupta2125** [comment]
sorry to be mis convenience
so will you assigned it to me?

**Comment by harshgupta2125** [comment]
brother i cant do anything in this it doesn;t work shows only loop of
processing
[image: image.png]

could you suggest me what to do in this

**Comment by Zedoman** [comment]
@harshgupta2125  whats the update?
