### ISSUE TITLE
🧑‍💻: Add Cryptocurrency Data API under Programs for API

### ISSUE THREAD

**Issue by nidhi2026** [Avdhesh-Varshney/Jarvis#153]
:red_circle: **Title**: Add Cryptocurrency Data API under Programs for API
:red_circle: **Enhancement Aim**:  This feature will be useful for users looking to fetch crypto market data in their applications.
:red_circle: **Changes**: 
- Integrate a cryptocurrency data API to enhance the repository by providing real-time cryptocurrency information
- View trending cryptocurrencies.
- Search for specific cryptocurrencies.
- public companies bitcoin/Ethereum holdings etc

### Screenshots 📷
on rough overview, something like: (the base looks of cryptos)
![image](https://github.com/user-attachments/assets/cee479fa-51bd-4d53-84ed-fb03065b71d4)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue:**
- Full name : Nidhi
- What is your participant role? GSSOC-ext Contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by nidhi2026** [comment]
@Avdhesh-Varshney 
Can this be added to api programs, if yes, can i work on it

**Comment by nidhi2026** [comment]
This is the final look of CryptosAPI
![image](https://github.com/user-attachments/assets/11a3f070-50a8-4b6e-a9b0-1c84f9a130bc)

and here is a video of an overview of all changes reflected in frontend

https://github.com/user-attachments/assets/98e36a67-c2e0-447a-bed2-fee9944022cb

Is there any change which I should do or it is good to go, if yes, can i make a pr for this

**Comment by Sunny1198** [comment]
hi @nidhi2026 , actually I am too working on jarvis(adding a game) and wanted to check whether it's working or not and I'm stuck at signup/login and unable to figure out how to get in. I'm a beginner at this so could you please help me out. Thanks
