### ISSUE TITLE
📃: Add scientific calculator

### ISSUE THREAD

**Issue by Aditijainnn** [Avdhesh-Varshney/Jarvis#154]
:red_circle: **Title**:  scientific calculator
:red_circle: **Brief Explanation**:  that calculate degree, power, radians

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Aditi
- What is your participant role?  gssoc ext and hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Moses-Mk** [comment]
please assign to me this task, I already submitted a PR for calculator API for this project, I can definitely solve another calculator problem. Thanks

**Comment by Avdhesh-Varshney** [comment]
This issue is already present [here](https://github.com/Avdhesh-Varshney/Jarvis/issues/81). Don't raise the same issue.
