### ISSUE TITLE
🧑‍💻: Improving Security for Jarvis AI Assistant

### ISSUE THREAD

**Issue by BondadaSusanthi** [Avdhesh-Varshney/Jarvis#160]
:red_circle: **Improving Security for Jarvis AI Assistant**: 
:red_circle: **I would like to propose a series of security enhancements for the Jarvis virtual AI assistant to ensure the safety and integrity of user data. As the application handles sensitive user information, it is crucial to implement robust security measures to protect against potential threats and vulnerabilities.**: 
:red_circle: **1)Two-Factor Authentication (2FA): Implement 2FA to add an extra layer of security during the login process, requiring users to provide a second form of verification.
2)Password Hashing: Ensure that passwords are hashed using a strong algorithm (e.g., bcrypt) before storing them in the database to protect user credentials.**: 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Bondada Susanthi
- What is your participant role? 
GSSOC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Password hashing is already implemented using bcrypt. 2FA is not required.
