### ISSUE TITLE
Lack of Unit Tests for Voice Command Processing

### ISSUE THREAD

**Issue by protham02** [Avdhesh-Varshney/Jarvis#162]
The repository currently lacks unit tests for critical features, such as voice command processing and error handling. This can lead to untested code paths, increasing the risk of bugs and regressions as the project scales. Implementing unit tests for valid and invalid command cases will ensure stability and reliability.

**Comment by Avdhesh-Varshney** [comment]
At now, this is not required because after transforming my project in python package, unit tests will be required.
Thanks for your interest.
