### ISSUE TITLE
Redirect to the login page after creating an account

### ISSUE THREAD

**Issue by Venuchander** [Avdhesh-Varshney/Jarvis#17]
# Automatically redirects to the login page after signing up.

![image](https://github.com/Avdhesh-Varshney/Jarvis/assets/106867270/400c1100-e48e-417d-b94a-6dc29cb27e58)

**Comment by Venuchander** [comment]
Assign me this issue under SSOC'24

**Comment by Avdhesh-Varshney** [comment]
@Venuchander go ahead.
