### ISSUE TITLE
add intro animation at the start 

### ISSUE THREAD

**Issue by AnushkaS77** [Avdhesh-Varshney/Jarvis#171]
hi... i would like to add an intro something like netflix before the home page opens up
ive worked with multiple projects 
example is given below

https://github.com/user-attachments/assets/0cb56710-b57e-4db8-abaf-3a2589b065b2

**Comment by HiyaGurbani** [comment]
I would like to work on it. Kindly assign it to me.

**Comment by Zedoman** [comment]
@AnushkaS77 whats the update?

**Comment by AnushkaS77** [comment]
@Zedoman kindly check for the pr ive raised....i did my best to make changes only in home.py as said before
