### ISSUE TITLE
🐛:  Find IP and My Location program under simple program doesn't output correct result on deployed site

### ISSUE THREAD

**Issue by nidhi2026** [Avdhesh-Varshney/Jarvis#174]
:red_circle: **Title**: Find IP program under the simple program doesn't output correct result on deployed site
:red_circle: **Bug**: 
While running I am getting this result, on the deployed version, 
![image](https://github.com/user-attachments/assets/441f7755-afa1-4576-864a-b14b5e2892a8)
same goes for My location where it again uses ipify 
![image](https://github.com/user-attachments/assets/486bf7f0-7b2b-4eb2-932a-b3a208c376ad)

as the streamlit cloud server where the project is hosted will make the request and ipify will take that server as the browser making the request, thus displaying its data.
locally running it gives correct as server and client will be the same
:red_circle: **Changes**:  
Making a direct call from ipify, so it would show IP address from user browsing that site instead of server on which this application is deployed using iframe

### Screenshots 📷
Preview of Issue
https://github.com/user-attachments/assets/9910d180-5ade-4ff2-88c8-2819ac7b294f

https://github.com/user-attachments/assets/40f97c3e-7271-450c-9c69-c4132424cab5

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Nidhi
- What is your participant role? GSSOC ext contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@nidhi2026 you will using any api key to get IP address. As on deployment, It can only gives IP address of streamlit server, Dalles, US. If so, reach out #30

**Comment by nidhi2026** [comment]
I tried using iframe of HTML to make call to ipify. calling ipify directly was making request from streamlit's server in US, but using iframe which runs in browser, 
` st.markdown('iframe src="ipify URL">....`
I used it and was getting same results as searching for my IP on a [website](https://whatismyipaddress.com/) on internet 
I have also tested this and deployed a small application on streamlit: https://clawskull.streamlit.app/
though the styling is not much great, but the data by iframe is correct, I think

**Comment by nidhi2026** [comment]
we can get public ipv6 and ipv4 address
@Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
It's really a good work. Go ahead 👍

**Comment by nidhi2026** [comment]
So should i work on the `find ip` or on `my location` too,

**Comment by nidhi2026** [comment]
@Avdhesh-Varshney 
This is the find ip part
![image](https://github.com/user-attachments/assets/2f87e195-8e32-4e0d-ac05-8a1b6620f84f)

for My Location, I have one doubt, will it show the details of the session user or we will enter an IP address like the image below, and the result will be according to that.
![image](https://github.com/user-attachments/assets/8bc58447-f216-4b63-a26e-1ec760ee31b3)
