### ISSUE TITLE
Change in Greeting Message

### ISSUE THREAD

**Issue by ShreeluSantosh** [Avdhesh-Varshney/Jarvis#18]
*Why this issue*
I noticed that Jarvis' greeting is not inclusive:
<img src="https://github.com/Avdhesh-Varshney/Jarvis/assets/94289402/cad36b8f-b7ea-49b2-899a-e998d9a80145">

*Proposal*
I plan to modify greeting.py to drop 'Sir' from the greeting messages, and replace it with the username.

Program: SSOC

**Comment by Avdhesh-Varshney** [comment]
@ShreeluSantosh go ahead.

**Comment by ShreeluSantosh** [comment]
Pull request: #19

**Comment by ShreeluSantosh** [comment]
PR created - #22
