### ISSUE TITLE
🐛: My Location throw error when associated city, region not found

### ISSUE THREAD

**Issue by nidhi2026** [Avdhesh-Varshney/Jarvis#196]
:red_circle: **Title**: My Location throw error when associated city, region not found
:red_circle: **Bug**: city, region not found for some IPs
:red_circle: **Changes**:  
Handling the attributes presence through python, so error wont be thrown
As the geo API doesn't mentioned about availability of attributes, I didn't add the check. I was trying for a new IP, it threw below error. I should have checked for other IPs as well. 
Also I plan to include the that IP organisation name and asn, continent code too.

### Screenshots 📷
![image](https://github.com/user-attachments/assets/4b2a1e31-9700-4664-b84f-90c5d8707856)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Nidhi
- What is your participant role? Gssoc-ext contributor

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@nidhi2026 join https://discord.gg/tSqtvHUJzE server
