### ISSUE TITLE
🧑‍💻: Add Table of Contents to README

### ISSUE THREAD

**Issue by T-Fathima** [Avdhesh-Varshney/Jarvis#199]
Currently, the README lacks a table of contents, making it challenging for users to navigate sections quickly. Adding a table of contents will enhance readability and allow users to locate information faster.
@Avdhesh-Varshney I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

**Comment by Moses-Mk** [comment]
Assign this to me
