### ISSUE TITLE
Adding contributing.md file

### ISSUE THREAD

**Issue by Arpcoder** [Avdhesh-Varshney/Jarvis#2]

**Comment by AbhishekMohanKr** [comment]
Hey can you assign me this issue.

**Comment by Avdhesh-Varshney** [comment]
@Arpcoder mention in which open source program are you participated?
And your name too.

**Comment by Arpcoder** [comment]
> @Arpcoder mention in which open source program are you participated? And your name too.

Name- Arpna
I have opened this under SSOC

**Comment by Avdhesh-Varshney** [comment]
@Arpcoder go ahead.

**Comment by INam1995** [comment]
#SSOC
@Avdhesh-Varshney can you please assign this issue to me under SSOC'24
