### ISSUE TITLE
📃: Add URL Shortener

### ISSUE THREAD

**Issue by parshvi1508** [Avdhesh-Varshney/Jarvis#201]
:red_circle: **Title**: Add URL Shortener
:red_circle: **Aim**: Add url shortening service to simple programs to Jarvis
:red_circle: **Brief Explanation**: The simple program takes a url as input from the user and returns a shortened url.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/3791b8d4-cb26-421a-a149-34506b283a18)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Parshvi Jain
- What is your participant role?: hacktoberfest & GSSOC extended 

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by parshvi1508** [comment]
@Avdhesh-Varshney @Zedoman 
I would appreciate it if you could take a moment to review it at your convenience. Your insights would be incredibly valuable.

**Comment by Zedoman** [comment]
go for it @parshvi1508
