### ISSUE TITLE
🧑‍💻: Enhancing current text-to-image generator program to Speech/text-to-image generator

### ISSUE THREAD

**Issue by jaidh01** [Avdhesh-Varshney/Jarvis#206]
:red_circle: **Title**: Enhancing current text-to-image generator program to Speech/text-to-image generator
:red_circle: **Enhancement Aim**: User can generate images through their voice
:red_circle: **Changes**: 

With the help of a speech recognition library, I will add an option through which users will be able to generate images using their voice.

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Jai Dhingra
- What is your participant role? GSSOC-24 Hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Provide both type of options to the user either using text or speech
