### ISSUE TITLE
🧑‍💻: Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [Avdhesh-Varshney/Jarvis#212]
:red_circle: **Title**:  Enhancement Of Document
:red_circle: **Enhancement Aim**:  To make the document in a more structured and organised manner with some additional contents
:red_circle: **Changes**: 

Wanted to do the following changes :-

1) Enhance the project structure
2) Add star our repository section
3) Add the project structure
4) Add need help with the basics section
5) Enhance the pull request steps section
6) Add additional method of contributing through GitHub desktop section
7) Add good coding practices section
8) Add the pull request rules section
9) Add the issue process section

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Milan P Samuel
- What is your participant role? 
 GSSOC extend , Hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
Not required.
