### ISSUE TITLE
🧑‍💻: Completing the Todo in PDFToolbox

### ISSUE THREAD

**Issue by shrehs** [Avdhesh-Varshney/Jarvis#215]
:red_circle: **Title**:  Completing the Todo in PDFToolbox
:red_circle: **Enhancement Aim**: Completion of the code
:red_circle: **Changes**:  Adding merge PDF, splitPDF, rotatePDF, encryptPDF, decryptPDF functions

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Shreya H S
- What is your participant role?  GSSOC-Ext, Hacktoberfest

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by shrehs** [comment]
Could please assign this to me, Shreya H S under GSSOC-Ext and Hcaktoberfest

**Comment by Avdhesh-Varshney** [comment]
Don't raise the pr until not assigned
