### ISSUE TITLE
🐛: Bug: Formatting and Content Issues in README.md

### ISSUE THREAD

**Issue by imDarshanGK** [Avdhesh-Varshney/Jarvis#220]
I've identified some issues in the README.md file that could be improved to enhance clarity, security, and overall presentation. Here are the details:

1} Inconsistent Badge Colors:
The color scheme used for the badges does not seem to align with typical usage. For example, the automation badge is red, which might not clearly indicate its purpose.

2} Redundant Sections:
The sections like "Overview" and "Core Features" could benefit from additional descriptions or bullet points for clarity.

3} Security Concerns:
The example login credentials for User, Admin, and Super Admin are publicly available. It is advisable to either remove these or note that they are for testing purposes only.

4} Formatting Issues:
Some sections may require better spacing and formatting for readability. Consistency in section headings and layout will improve the document's professionalism.

5} Missing Links:
There are opportunities to link to additional documentation or resources that could help users better understand the project.

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

@Avdhesh-Varshney

**Comment by Kritika75** [comment]
hey @imDarshanGK can you assign me this under KWoc'24??

**Comment by Avdhesh-Varshney** [comment]
Sorry, But this issue can't be considered.
