### ISSUE TITLE
🧑‍💻: Fixing invalid email addresses on the signup page

### ISSUE THREAD

**Issue by Venuchander** [Avdhesh-Varshney/Jarvis#23]
:red_circle: **Title** : Fix Invalid Email Address Handling

:red_circle: **Enhancement Aim** : Ensure that the system correctly identifies and manages invalid email addresses to improve data integrity and user communication.

:red_circle: **Changes** :
- Implement validation checks for email format during data entry.
- Update database to flag and handle existing invalid email entries.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/Jarvis/assets/106867270/90c32df6-37de-4ad5-9be6-56beac6f24e2)

***********************************************************************
:white_check_mark: **Contributor Details :**
- Full name : Venuchander
- Program: SSOC

***********************************************************************

**Comment by Venuchander** [comment]
Please assign this issue to me under SSOC'24.

**Comment by daanishmittal24** [comment]
assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@Venuchander this msg throw to maintain the uniqueness of the email i.e. 1 account per email.
