### ISSUE TITLE
🐛: Cursor changes to text on hovering over options 

### ISSUE THREAD

**Issue by satyam969** [Avdhesh-Varshney/Jarvis#233]
:red_circle: **Title**: 
:red_circle: **Bug**: Cursor changes to text on hovering over options
:red_circle: **Changes**:  Will Turn it To pointer

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Priya Raj
- What is your participant role?  GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
No need. This just increase the load of the website
