### ISSUE TITLE
🐛: Navbar Not Responsive On Mobile Phones

### ISSUE THREAD

**Issue by satyam969** [Avdhesh-Varshney/Jarvis#234]
:red_circle: **Title**: NavBar Not Responsive
:red_circle: **Bug**:On Mobile Phone Options in Navbar Not Visible 
:red_circle: **Changes**:  Will make a Responsive NavBar 

### Screenshots 📷
![image](https://github.com/user-attachments/assets/47be929a-349a-4f18-af45-c7bd8dadb189)

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Priya Raj
- What is your participant role? GSSOC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
I think you raise issue in wrong project.
