### ISSUE TITLE
🧑‍💻: upgrade live location detection and weather detection

### ISSUE THREAD

**Issue by Nayan2003** [Avdhesh-Varshney/Jarvis#238]
:red_circle: **Title**: upgraded live location detection and weather detection
:red_circle: **Enhancement Aim**: in this enhancement we are going to add location detection and weather climate detection using voice command ., without manually input of API key so this is big  pluse point ✅😊
:red_circle: **Changes**: 
we add live location detection
we also add weather detection

### Screenshots 📷

NA

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  Nayan Khuje
- What is your participant role? 
CONTRIBUTOR at GSSoC 24 Extd
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

please assign me this task i did lot of hard work.. to do this task...

**Comment by Nayan2003** [comment]
and please add gssoc ext label . this is my first pull at working on project.. before that i just got point not did much

**Comment by Avdhesh-Varshney** [comment]
Never raise the pr until not assigned.

**Comment by Nayan2003** [comment]
ohk but mey i work on it ? @Avdhesh-Varshney ?

**Comment by Avdhesh-Varshney** [comment]
> ohk but mey i work on it ? @Avdhesh-Varshney ?

Program is ends. But if you want to work on it, go ahead.

**Comment by Nayan2003** [comment]
hiii , I  have added this feature using creating new branch ... #Enhancment branch ....so checkout this one

**Comment by Nayan2003** [comment]
and sorry for the delay ... i was busy with college exams
