### ISSUE TITLE
📃: Internet speed testing program

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#28]
:red_circle: **Title** : Internet speed test
:red_circle: **Aim** : To detecting the internet speed of internet or connected wifi.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by akarshghildyal** [comment]
can you assign this to me under SSOC ?

**Comment by karan-panda** [comment]
### Full name: Karan Pradeep Kumar Panda
### Role: SSOC
Can you please assign this issue to me.

**Comment by Avdhesh-Varshney** [comment]
@karan-panda go ahead.

**Comment by Avdhesh-Varshney** [comment]
@karan-panda what's the update? solve it within 1 day.

**Comment by karan-panda** [comment]
Yes, sir! 🫡
I will try my best to complete it within a day.

**Comment by akarshghildyal** [comment]
@Avdhesh-Varshney hello, can you look into this issue and assign it to me ?

**Comment by Avdhesh-Varshney** [comment]
@akarshghildyal go ahead.

**Comment by akarshghildyal** [comment]
@Avdhesh-Varshney I am unable to get past some error, you can unassign this to me. Thanks

**Comment by Avdhesh-Varshney** [comment]
@parshvi1508 keep it inside `simplePrograms` ok
