### ISSUE TITLE
📃: Timer Python program

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#29]
:red_circle: **Title** : Timer program
:red_circle: **Aim** : Create a timer program to notify the user on fixed timer.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by akarshghildyal** [comment]
Can you assign this to me under SSOC ?

**Comment by Avdhesh-Varshney** [comment]
@akarshghildyal go ahead.
