### ISSUE TITLE
📃: GPT api based chatbot

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#31]
:red_circle: **Title** : GPT bot
:red_circle: **Aim** : Create a chatgpt based chatbot for user using api.
:red_circle: **Brief Explanation** : Keep it inside chatbots directory.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by krishnasharmak05** [comment]
@Avdhesh-Varshney, I would like to work on this issue.

✅ To be Mentioned while taking the issue :

Full name : Krishna Sharma K
What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.) - SSOC

**Comment by Avdhesh-Varshney** [comment]
@krishnasharmak05 go ahead.

**Comment by Avdhesh-Varshney** [comment]
@krishnasharmak05 what's the update? solve it within 1 day.

**Comment by imsuraj675** [comment]
@Avdhesh-Varshney If @krishnasharmak05 is not working on this issue. Please assign me this issue under SSOC. I will implement the chat bot using Gemini API

**Comment by krishnasharmak05** [comment]
> @krishnasharmak05 what's the update? solve it within 1 day.
> @Avdhesh-Varshney If @krishnasharmak05 is not working on this issue. Please assign me this issue under SSOC. I will implement the chat bot using Gemini API

@Avdhesh-Varshney , @imsuraj675, I am nearly done with it. Will make a PR today.
