### ISSUE TITLE
📃:  Adding a diabetes test feature using DL model

### ISSUE THREAD

**Issue by ChiragGupta16** [Avdhesh-Varshney/Jarvis#34]
🔴 Title :  Adding diabetes test program
🔴 Aim : To detect if a patient has diabetes or not 
🔴 Brief Explanation :
I will train a model to detect diabetes. I will then collect all essential information from user , pass it to the model and return the output.

Screenshots 📷

✅ To be Mentioned while taking the issue :

Full name : Chirag Gupta
What is your participant role? SSOC
Happy Contributing 🚀

All the best. Enjoy your open source journey ahead. 😎

**Comment by ChiragGupta16** [comment]
@Avdhesh-Varshney please assign this issue to me.

**Comment by Avdhesh-Varshney** [comment]
@ChiragGupta16 It's a great edition. go ahead.
