### ISSUE TITLE
📃: Adding a feature to detect Brain tumor from MRI scan using DL model

### ISSUE THREAD

**Issue by ChiragGupta16** [Avdhesh-Varshney/Jarvis#36]
:red_circle: **Title** : Chirag Gupta
:red_circle: **Aim** :  Adding a feature to detect Brain tumor from MRI scan using DL model
:red_circle: **Brief Explanation** :
I will train a model to detect brain tumor. I will then collect the MRI scan result from user, pass it to the model and return the output.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Chirag Gupta
- What is your participant role? : Contributor SSoC
***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ChiragGupta16** [comment]
@Avdhesh-Varshney  Please assign this issue to me

**Comment by Avdhesh-Varshney** [comment]
@ChiragGupta16 go ahead.
