### ISSUE TITLE
[Feat]: Add Jokes in Basic Programs

### ISSUE THREAD

**Issue by imsuraj675** [Avdhesh-Varshney/Jarvis#4]
Can you please elaborate, what feature you want to add in the Basic program Jokes section. I want to contribute on this under SSOC'24.

**Comment by Avdhesh-Varshney** [comment]
@imsuraj675 go ahead. But before raising the pr join the project discord server.

**Comment by Avdhesh-Varshney** [comment]
@imsuraj675 are you working on it?
