### ISSUE TITLE
📃: Alarm Program

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#43]
:red_circle: **Title** : Alarm Program
:red_circle: **Aim** : Create a alarm application to notify user on the ping or set up time. 
:red_circle: **Brief Explanation** :
- Take time inputs
- take any message to flash on times up.
- store any link or note
- create a interactive user interface

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by akarshghildyal** [comment]
Hello, I want to contribute to this under SSOC. 
Thanks.

**Comment by parshvi1508** [comment]
@Avdhesh-Varshney I'm Parshvi Jain, participating in SSOC and I’d like to add alarm functionality to the project. I'll create a new file alarm_app.py  in simple programs for this feature, including user input for setting alarms and notifications.

**Comment by Avdhesh-Varshney** [comment]
@parshvi1508 go ahead.
