### ISSUE TITLE
📃: Play your music program

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#46]
:red_circle: **Title** : Play your music program
:red_circle: **Aim** : Get the details of music features from the user and by using any music api get the data according to the users requiments.
:red_circle: **Brief Explanation** :
- Use any musics api for the database
- If free api not found, Provide the option for the api addition and proper guide to get their own api key
- Create a proper form for the user to the get the required fields.
- Show the recommendation either on the basis of category of musics or from actor/actress and many more.
- UI should be looks nice and interactive

**NOTE:** Use of API Key is mandatory. No hard coded database is used.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by akarshghildyal** [comment]
Hello @Avdhesh-Varshney . I would like to work on this under Hacktoberfest. Thanks.
