### ISSUE TITLE
📃: Watch News Program

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#47]
:red_circle: **Title** : Watch your news program
:red_circle: **Aim** : Get the current news details from any api and integrate it with the streamlit app
:red_circle: **Brief Explanation** :
- Use any news api for the database
- If free api not found, Provide the option for the api addition and proper guide to get their own api key
- Create a card component to showcase the image related to news and it's title and a small description
- Along with it provide the link to read more about this news.
- UI should be looks nice and interactive

**NOTE:** Use of API Key is mandatory. No hard coded database is used.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Moses-Mk** [comment]
I am interested in this, please assign it to me

**Comment by Avdhesh-Varshney** [comment]
I think it's already completed. Sorry for inconvenience.
