### ISSUE TITLE
📃: Temperature details of any place

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#49]
:red_circle: **Title** : Weather condition of any place
:red_circle: **Aim** : Get the real time data of weather condition of any place using any api key.
:red_circle: **Brief Explanation** :
- Use any weather api for the database
- If free api not found, Provide the option for the api addition and proper guide to get their own api key
- Create a card component to showcase the image related to weather condition, a title and all the details like temperature, humidity, air wind speed, night temperature, etc.
- UI should be looks nice and interactive

**NOTE:** Use of API Key is mandatory. No hard coded database is used.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by akarshghildyal** [comment]
@Avdhesh-Varshney I would like to work on this under SSOC.
Thanks.
