### ISSUE TITLE
📃: Tic Tac Toe Game 

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#50]
:red_circle: **Title** : Tic Tac Toe Game
:red_circle: **Aim** : Create a tic tac toe game using python and streamlit application.
:red_circle: **Brief Explanation** :
- UI should be looks nice and interactive

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Dhiv123** [comment]
Hello @Avdhesh-Varshney 
I am Dhivyasree Thangamani, I would like to work on this issue.
Please assign it to me under SSOC'24.

**Comment by Avdhesh-Varshney** [comment]
@Dhiv123 go ahead.
