### ISSUE TITLE
📃: Bar Code Generator Program

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#51]
:red_circle: **Title** : Bar Code Generator Program
:red_circle: **Aim** : Create a bar code generator program using python and streamlit application.
:red_circle: **Brief Explanation** :
- take the required data from the user for bar code creation
- UI should be looks nice and interactive
- user will able to download the bar code generated, so create a download button

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by imsuraj675** [comment]
@Avdhesh-Varshney  I want to work on this issue. Please assign this issue to me.

**Comment by Avdhesh-Varshney** [comment]
@imsuraj675 go ahead.

**Comment by imsuraj675** [comment]
@Avdhesh-Varshney Can you specify that this program will be under which section? CasualPrograms, with the timer function?

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney Can you specify that this program will be under which section? CasualPrograms, with the timer function?

From your question, I'm thinking to create a new category for image generator programs. Have you any name for the category?
Join discord server for faster communication https://discord.gg/tSqtvHUJzE
