### ISSUE TITLE
📃: QR Code generator

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#52]
:red_circle: **Title** : QR Code Generator Program
:red_circle: **Aim** : Create a QR code generator program using python and streamlit application.
:red_circle: **Brief Explanation** :
- take the required data from the user for bar code creation either text, links, number, phone number, etc.
- UI should be looks nice and interactive
- user will able to download the bar code generated, so create a download button

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by vishalmaurya850** [comment]
Assign this issue to me
Vishal Maurya
SSOC 24

**Comment by Avdhesh-Varshney** [comment]
@vishalmaurya850 go ahead.

**Comment by vishalmaurya850** [comment]
Please it will work independently or inside Jarvis??

**Comment by Avdhesh-Varshney** [comment]
> Please it will work independently or inside Jarvis??

It must be integrate with Jarvis
