### ISSUE TITLE
📃: Password Generator Program

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#53]
:red_circle: **Title** : Password Generator Program
:red_circle: **Aim** : Create a password generator program using python and streamlit application.
:red_circle: **Brief Explanation** :
- take the required data from the user for password generator either hard, medium, easy level password, length, number?, alpha?, etc.
- UI should be looks nice and interactive
- user will able to copy the generated password in your clipboard

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by akarshghildyal** [comment]
Hello, I would like to work on this under SSOC.
Thankyou.

**Comment by Avdhesh-Varshney** [comment]
@akarshghildyal go ahead.
