### ISSUE TITLE
Adding better ui 

### ISSUE THREAD

**Issue by Chelseasingla1** [Avdhesh-Varshney/Jarvis#6]
![image](https://github.com/Avdhesh-Varshney/Jarvis/assets/129886894/d812fdc8-9735-4926-967b-6cc6439ef5b1)

I would like to add better ui in this page maybe by adding some icons. Please assign this issue under SSOC'24.

**Comment by Avdhesh-Varshney** [comment]
@Chelseasingla1 go ahead.

**Comment by vHarshita15** [comment]
I want to work on this. Please Assign this to me

**Comment by Avdhesh-Varshney** [comment]
@vHarshita15 go ahead.

**Comment by Avdhesh-Varshney** [comment]
@vHarshita15 what's the update of dashboard?

**Comment by sharmaviniii** [comment]
I would like to work on this, please assign this to me!
name : Vanshika Sharma
contributor

**Comment by Avdhesh-Varshney** [comment]
@sharmaviniii PR will be merged on good looking.
**Hint:** *Explore the streamlit documentation.*

**Comment by sharmaviniii** [comment]
please let me know where can I find the code ?

**Comment by Avdhesh-Varshney** [comment]
> please let me know where can I find the code ? I've checked the streamlit documnetation

Hint tells you that explore the other features of the streamlit not point out any particular code!
