### ISSUE TITLE
📃: Handwritten Digit Recognition using CNN

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#63]
:red_circle: Title : Handwritten Digit Recognition using CNN
:red_circle: Aim : Develop a Convolutional Neural Network (CNN) model to recognize handwritten digits from images.
:red_circle: Brief Explanation :

- Use the MNIST dataset, which contains images of handwritten digits (0-9).
- Train a CNN model on the dataset to recognize the digits.
- Create a UI for users to upload images of handwritten digits and display the recognition results.
- Ensure the UI is user-friendly and provides accurate results.

Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by payo101** [comment]
Hi @Avdhesh-Varshney , Could I have a look at this issue?

**Comment by payo101** [comment]
Hi @Avdhesh-Varshney , what kind of photos can we expect? because the mnist dataset has a very small resolution of 28x28. I can try to use a different dataset if there is one with a larger resolution.

**Comment by kush1311** [comment]
I would like to work on it please kindly assign me

**Comment by Avdhesh-Varshney** [comment]
> Hi @Avdhesh-Varshney , what kind of photos can we expect? because the mnist dataset has a very small resolution of 28x28. I can try to use a different dataset if there is one with a larger resolution.

Scan the document and extract the digits by identifying from the uploaded image.

**Comment by payo101** [comment]
Hey @Avdhesh-Varshney , I have created a PR for the changes: https://github.com/Avdhesh-Varshney/Jarvis/pull/120, Please review and comment any neccesary changes.
