### ISSUE TITLE
📃: Text Summarization using NLP

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#64]
:red_circle: Title : Text Summarization using NLP
:red_circle: Aim : Create a Natural Language Processing (NLP) model to summarize long pieces of text into concise summaries.
:red_circle: Brief Explanation :

- Use a dataset of articles or documents to train the model.
- Implement an NLP model (e.g., using transformers) to generate summaries.
- Create a UI for users to input text and receive a summarized version.
- Ensure the UI is clean and easy to use, providing clear summaries quickly.

Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by imsuraj675** [comment]
I want to work on this issue, assign me this issue under SSOC'24

**Comment by Avdhesh-Varshney** [comment]
@imsuraj675 go ahead.

**Comment by dish04** [comment]
Hey, Im down to work on this for Hacktober Fest.

**Comment by Avdhesh-Varshney** [comment]
@dish04 I can assign you but you should well aware that hacktoberfest is counted only those prs which are raised and merged in october.

**Comment by Rajesh9998** [comment]
@Avdhesh-Varshney  I would like to express my interest in working on this issue. My proposal for addressing it is to utilize Large Language Models (LLMs) through the Groq API, as I believe this approach will provide a faster solution. I am eager to contribute to this project under the GSSoC'24 Extended Edition.

**Comment by Avdhesh-Varshney** [comment]
@Rajesh9998 You are proposing for an API services, you can raise another issue with API services? But this issue is related to model building.

**Comment by Peart-Guy** [comment]
Hi @Avdhesh-Varshney
Name : Ankan
Participant Role: Contributor (GSSoC'24-Extd)
I would like to work on this project using Gensim and NLTK module in python

**Comment by aakashmohole** [comment]
I want to work on this issue, assign me this issue

**Comment by Peart-Guy** [comment]
I have done the work. Kindly Check it out.
