### ISSUE TITLE
📃: Face Mask Detection System

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#65]
:red_circle: **Title** : Face Mask Detection System  
:red_circle: **Aim** : Develop a system to detect whether people are wearing face masks using a deep learning model.  
:red_circle: **Brief Explanation** :  
- Collect a dataset of images with and without face masks.
- Train a CNN model to recognize face masks in real-time.
- Create an interface to upload images or use a webcam for real-time mask detection.
- Ensure the UI is intuitive and visually appealing.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)  

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ChiragGupta16** [comment]
Please assign this to me.

I will train a model to detect masks and use OpenCV to  do real time mask detection in both laptop and external webcams.
It will have options for both images and real time video.

 Name : Chirag Gupta
 Role : Contributor, SSoC

**Comment by Avdhesh-Varshney** [comment]
@ChiragGupta16 go ahead.
