### ISSUE TITLE
📃: Real-Time Object Detection in Videos

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#67]
:red_circle: **Title** : Real-Time Object Detection in Videos  
:red_circle: **Aim** : Implement a system for real-time object detection in videos using computer vision techniques.  
:red_circle: **Brief Explanation** :  
- Utilize a pre-trained object detection model like YOLO or SSD.
- Develop a pipeline to process frames from videos and detect objects.
- Display bounding boxes around detected objects in real-time.
- Ensure efficient processing to maintain real-time performance.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :  
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)  

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by sahuf2003** [comment]
I can work on this

**Comment by Avdhesh-Varshney** [comment]
@sahuf2003 go ahead.
