### ISSUE TITLE
Adding Readme Files within each folder

### ISSUE THREAD

**Issue by Akarsh-dundun** [Avdhesh-Varshney/Jarvis#7]
I would like to document the whole repo with more comprehensive readme files so that documentation can enable future coders to understand the functionality of each folder properly.

I am a contributor at SSOC '24

Contributor Name: Akarsh Gupta

**Comment by Avdhesh-Varshney** [comment]
@Akarsh-dundun go ahead. But before raising the pr, discuss about it on project discord server. Link is present in the Main README file.

**Comment by Akarsh-dundun** [comment]
Okay got it @Avdhesh-Varshney !! Will do
