### ISSUE TITLE
📃: Quote of the Day

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#71]
:red_circle: **Title** : Quote of the Day  
:red_circle: **Aim** : Integrate a feature to display a new inspiring quote each day in the Streamlit-based Jarvis application.  
:red_circle: **Brief Explanation** :  
- Utilize a quote API to fetch a new quote daily.
- Implement a component in Streamlit to display the daily quote along with its author.
- Ensure the UI is aesthetically pleasing and interactive, with a refreshing quote displayed prominently.
  
### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Dhiv123** [comment]
Hello, @Avdhesh-Varshney,
I am Dhivyasree Thangamani,
 Pls assign this issue to me under SSOC'24.

**Comment by Dhiv123** [comment]
Hello @Avdhesh-Varshney ,
I am Dhivyasree Thangamani,
Pls assign this issue to me under SSOC'24.

**Comment by akarshghildyal** [comment]
@Avdhesh-Varshney would zenquotes api work for this ? kindly assign this to me under 'SSOC

**Comment by Avdhesh-Varshney** [comment]
> @Avdhesh-Varshney would zenquotes api work for this ? kindly assign this to me under 'SSOC

If it's free to use, go ahead.
