### ISSUE TITLE
📃: Currency Converter

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#73]
:red_circle: **Title** : Currency Converter  
:red_circle: **Aim** : Integrate a feature to convert currencies based on real-time exchange rates in the Streamlit-based Jarvis application.  
:red_circle: **Brief Explanation** :  
- Utilize a currency exchange rate API to fetch real-time conversion rates.
- Implement a user interface where users can input the amount, select currencies to convert from and to, and get the converted amount.
- Ensure the UI is intuitive and provides clear feedback on currency conversions.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by akarshghildyal** [comment]
I would like to work on this under SSOC.

**Comment by Avdhesh-Varshney** [comment]
@akarshghildyal go ahead.
