### ISSUE TITLE
📃: Unit Converter

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#74]
:red_circle: **Title** : Unit Converter  
:red_circle: **Aim** : Integrate a feature to convert between different units of measurement in the Streamlit-based Jarvis application.  
:red_circle: **Brief Explanation** :  
- Utilize APIs or libraries to handle unit conversions for various categories such as length, weight, volume, temperature, etc.
- Implement a user interface where users can input a value and select units to convert from and to.
- Ensure accurate conversion calculations and display the converted value to the user.
- Design the UI to be intuitive and user-friendly, allowing for easy selection and conversion of units.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by akarshghildyal** [comment]
I would like to work on this under SSOC. Thanks

**Comment by Avdhesh-Varshney** [comment]
@akarshghildyal go ahead.
