### ISSUE TITLE
📃: Daily Horoscope Display

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#77]
:red_circle: **Title** : Daily Horoscope Display  
:red_circle: **Aim** : Integrate a feature to display daily horoscope predictions in the Streamlit-based Jarvis application.  
:red_circle: **Brief Explanation** :  
- Utilize a horoscope API to fetch daily predictions based on zodiac signs.
- Implement a functionality where users can select their zodiac sign from a dropdown menu.
- Display the daily horoscope prediction including general advice or insights for the selected zodiac sign.
- Ensure the UI is user-friendly with clear presentation of horoscope information.
  
### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by akarshghildyal** [comment]
I would like to work on this under SSOC. Thanks
@Avdhesh-Varshney

**Comment by Avdhesh-Varshney** [comment]
@akarshghildyal go ahead.
