### ISSUE TITLE
📃: To-Do List

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#79]
:red_circle: Title : Simple To-Do List Application
:red_circle: Aim : Create a basic to-do list application in the Streamlit-based Jarvis application.
:red_circle: Brief Explanation :

- Develop a user interface where users can add tasks to a list, mark tasks as completed, and delete tasks.
- Implement functionality to store tasks locally within the application (using simple data structures like lists or dictionaries).
- Include features like task filtering (e.g., viewing all tasks, completed tasks, or pending tasks).
- Ensure the UI is clean, responsive, and easy to use.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by khushi25916** [comment]
name: khushi agrahari
role: ssoc

**Comment by Avdhesh-Varshney** [comment]
@khushi25916 go ahead.

**Comment by khushi25916** [comment]
hey can ask when i have too submit this?

**Comment by Avdhesh-Varshney** [comment]
> hey can ask when i have too submit this?

solve it within 5 days. Go with the description of labels of priority ok.

**Comment by khushi25916** [comment]
ok then

**Comment by khushi25916** [comment]
https://github.com/khushi25916/to_do-list.git
here please let me know if you need modification in this

**Comment by Avdhesh-Varshney** [comment]
> https://github.com/khushi25916/to_do-list.git here please let me know if you need modification in this

Integrate it with jarvis and submit a working video in pr

**Comment by parshvi1508** [comment]
I am Parshvi Jain.
I am interested in integrating To-Do list to Jarvis under hacktoberfest.
Kindly consider assigning this issue to me. I am ready to start and will provide regular updates.
