### ISSUE TITLE
📃: Calculator Integration

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Avdhesh-Varshney/Jarvis#80]
:red_circle: **Title** : Calculator Integration  
:red_circle: **Aim** : Integrate a simple calculator feature into the Streamlit-based Jarvis application.  
:red_circle: **Brief Explanation** :  
- Implement a basic calculator functionality that allows users to perform arithmetic operations (addition, subtraction, multiplication, division).
- Design a user interface with buttons for digits (0-9), operators (+, -, *, /), and other necessary controls (clear, equals).
- Ensure the calculator performs accurate calculations and displays results in a clear manner.
- Make the UI intuitive and responsive for easy interaction.

### Screenshots 📷

N/A

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : 
- What is your participant role? (Mention the Open Source Program name. Eg. GSSOC, SSOC, JWOC, etc.)

***********************************************************************

Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by ChiragAgg5k** [comment]
Hey there, I would like to work on this issue. My name is Chirag Aggarwal, and I am contributing for SSOC

**Comment by Avdhesh-Varshney** [comment]
@ChiragAgg5k go ahead.
