### ISSUE TITLE
🧑‍💻: Small issue regarding naming convention for the virtual environment

### ISSUE THREAD

**Issue by ChiragAgg5k** [Avdhesh-Varshney/Jarvis#83]
:red_circle: **Title** : Issue regarding naming convention for the virtual environment
:red_circle: **Enhancement Aim** : Improve environment setup for new users
:red_circle: **Changes** : 

As stated In the `README.md` file, you are required to name your virtual environment to be `env`:

```bash
   python -m venv env
   source env/bin/activate  # On Windows, use `env\Scripts\activate`
   ```

But in the`.gitignore` file, the environment folder being ignored is `myenv`

My suggestion is to simply rename the folder in either the readme file or gitignore file.

### Screenshots 📷

<img width="189" alt="Screenshot 2024-06-30 at 7 06 45 PM" src="https://github.com/Avdhesh-Varshney/Jarvis/assets/110609663/21b79d2c-d00e-45ab-b463-27f18956f1c2">

<img width="209" alt="Screenshot 2024-06-30 at 7 06 54 PM" src="https://github.com/Avdhesh-Varshney/Jarvis/assets/110609663/68dbd64e-70b1-4a5c-bd6a-338828ff06f0">

**Comment by Avdhesh-Varshney** [comment]
@ChiragAgg5k go ahead.
