### ISSUE TITLE
📃:  Depression Detection using Audio

### ISSUE THREAD

**Issue by ChiragGupta16** [Avdhesh-Varshney/Jarvis#87]
:red_circle: **Title** : Depression Detection using Audio
:red_circle: **Aim** : To detect if a person is in depression using his voice
:red_circle: **Brief Explanation** :

In this feature, we will take audio input directly or ask the user to speak. The recorded voice will be processed to digital form so that we get the signals in terms of amplitude and frequency using fourier transformation, which is the base for further transformations.
We will train the feature to work in English and Hindi, while it may work if it detects emotion in voice if user speaks in any other language.

Also, a new dataset will be created for this feature which will help us to train a model to detect depression. 

### Screenshots 📷

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name : Chirag Gupta 
- What is your participant role? Contributor, SSoC

***********************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by Avdhesh-Varshney** [comment]
@ChiragGupta16 go ahead. If you need any help, mention me on discord server.

**Comment by vishalmaurya850** [comment]
Assign issue to me with another issue #55 I will do both at the same time and because both issues are same and required same time and I am a Data Science student, so I contribute very perfectly on both the issue.
